services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
    command: gunicorn --bind 0.0.0.0:8000 main:app --workers 1 --reload --timeout 300 --log-level debug --capture-output --access-logfile -
