/**
 * Pokedex HQ theme — same token values as `pokedexHq.theme.css` for reuse in TS
 * (charts, canvas, inline styles, tests). When changing the palette, update both files.
 */
export const pokedexHqTheme = {
  colors: {
    surface: "#ffffff",
    "outline-variant": "#d2c5ab",
    "surface-dim": "#f3f0ef",
    "tertiary-container": "#b8d3ff",
    secondary: "#ef5350",
    error: "#ba1a1a",
    background: "#ffffff",
    "secondary-container": "#ffdad7",
    "surface-container-lowest": "#ffffff",
    "inverse-surface": "#313030",
    "on-primary-fixed": "#241a00",
    "on-tertiary": "#ffffff",
    "on-secondary-fixed": "#410004",
    "surface-container-low": "#f6f3f2",
    "inverse-primary": "#f2c000",
    primary: "#ffcb05",
    "surface-variant": "#f0eded",
    "error-container": "#ffdad6",
    "surface-bright": "#ffffff",
    "tertiary-fixed": "#d4e3ff",
    "on-secondary-fixed-variant": "#910816",
    "secondary-fixed-dim": "#ffb3ae",
    "surface-container-highest": "#e5e2e1",
    tertiary: "#155fa8",
    "surface-container-high": "#eae7e7",
    "on-secondary-container": "#410002",
    "on-tertiary-fixed-variant": "#004784",
    "on-error": "#ffffff",
    "on-tertiary-fixed": "#001c3a",
    "on-surface": "#1a1a1a",
    "surface-tint": "#745b00",
    "surface-container": "#f0eded",
    "inverse-on-surface": "#f3f0ef",
    "secondary-fixed": "#ffdad7",
    "primary-container": "#ffcb05",
    "on-error-container": "#93000a",
    "on-primary-container": "#241a00",
    "on-secondary": "#ffffff",
    "primary-fixed": "#ffe08d",
    "on-tertiary-container": "#0a5ba3",
    "primary-fixed-dim": "#f2c000",
    "on-primary-fixed-variant": "#584400",
    outline: "#80765f",
    "tertiary-fixed-dim": "#a4c8ff",
    "on-background": "#1a1a1a",
    "on-surface-variant": "#4e4632",
    "on-primary": "#1a1a1a",
  },
  spacing: {
    "section-gap": "48px",
    gutter: "16px",
    "stack-sm": "4px",
    unit: "8px",
    "container-padding": "24px",
    "stack-md": "12px",
  },
  radius: {
    DEFAULT: "0.25rem",
    lg: "0.5rem",
    xl: "0.75rem",
    full: "9999px",
  },
} as const

export type PokedexHqTheme = typeof pokedexHqTheme
